### ISSUE TITLE
Fix escape characters within response

### ISSUE THREAD

**Issue by lewismc** [lewismc/iPReS#25]
When I pretty print a JSON response I get the following
![screen shot 2015-04-13 at 2 04 36 am](https://cloud.githubusercontent.com/assets/1165719/7111131/37e7ef84-e181-11e4-99b8-348100c72719.png)
You can see here that forward slashed are not escaped back to normal format.

**Comment by cartermp** [comment]
Dumping the raw output to [this pretty printer](http://jsonprettyprint.com/json-pretty-printer.php) inserts the escapes.  That seems to be an issue with that application, as [this other pretty printer](http://jsonformatter.curiousconcept.com/) shows urls and things fine.

A few snippets from the raw output:

![reg-slashes](https://cloud.githubusercontent.com/assets/6309070/7119834/c4a18372-e1bd-11e4-9786-72aa332eddcb.PNG)
![urls](https://cloud.githubusercontent.com/assets/6309070/7119835/c8707076-e1bd-11e4-81c8-cacefc024889.PNG)
