### ISSUE TITLE
Implement logging in Jetty server

### ISSUE THREAD

**Issue by lewismc** [lewismc/iPReS#30]
Right now there is no logging in the server at all... this is extremely difficult for debugging server requests and what is actually happening (specifically whether or not Language Translation is actually taking place).
I propose we try the following
https://github.com/pjlegato/ring.middleware.logger

**Comment by cartermp** [comment]
I've got this implemented but can't find a log directory on my machine (Windows 8.1).  I'll commit this for now to see if it works on your end; I'll investigate other solutions when I get back home tonight if it doesn't work for you.

**Comment by lewismc** [comment]
Dynamite. Verified to work. Looking great.

**Comment by lewismc** [comment]
Excellent work @cartermp

**Comment by cartermp** [comment]
Good to hear!
